// <auto-generated />
using System;
using EkspozitaPikturave.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EkspozitaPikturave.Data.Migrations
{
    [DbContext(typeof(PikturatEKSContents))]
    partial class PikturatEKSContentsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EkspozitaPikturave.Models.Ekspozitat", b =>
                {
                    b.Property<int>("Id_Ekspozites")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Ekspozita")
                        .HasColumnType("int");

                    b.Property<string>("FotojaURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulli")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("uzerEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id_Ekspozites");

                    b.ToTable("Ekspozitat");
                });

            modelBuilder.Entity("EkspozitaPikturave.Models.Kritikat", b =>
                {
                    b.Property<int>("Id_Kritika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_Piktura")
                        .HasColumnType("int");

                    b.Property<string>("Id_Useri")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TekstiKritikes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Kritika");

                    b.ToTable("Kritikat");
                });

            modelBuilder.Entity("EkspozitaPikturave.Models.Pikturat", b =>
                {
                    b.Property<int>("IdPiktura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CmimiPiktures")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataPostimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Disponueshmeria")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Ekspozitat")
                        .HasColumnType("int");

                    b.Property<string>("ID_Useri")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Karakteristikat")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LLojiPiktures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Shporta")
                        .HasColumnType("int");

                    b.Property<string>("TitulliPiktures")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPiktura");

                    b.ToTable("Pikturat");
                });

            modelBuilder.Entity("EkspozitaPikturave.Models.Shporta", b =>
                {
                    b.Property<int>("Id_Shporta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Blerja")
                        .HasColumnType("bit");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id_Piktura")
                        .HasColumnType("int");

                    b.Property<string>("Id_UseriKlient")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id_Shporta");

                    b.ToTable("Shporta");
                });
#pragma warning restore 612, 618
        }
    }
}
